name: Continuous Integration

on:
  push:
    paths-ignore:
      - "**/README.md"
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  rust-checks:
    name: Rust Checks
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        action:
          - command: fmt
            args: --all -- --check --color always
          - command: clippy
            args: --all-targets --all-features --workspace -- -D warnings

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: nightly
          components: rust-src, rustfmt, clippy

      - name: Enable caching
        uses: Swatinem/rust-cache@v2

      - name: Generate or copy config
        run: |
          cp cfg.toml.example cfg.toml
          
      - name: Run command
        run: cargo ${{ matrix.action.command }} ${{ matrix.action.args }}

  build-test:
    needs: rust-checks
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v3

    - name: Install Rust for Xtensa
      uses: esp-rs/xtensa-toolchain@v1.5
      with:
        default: true
        ldproxy: true
        
    - name: Generate or copy config
      run: |
        cp cfg.toml.example cfg.toml
    
    - name: Run cargo check
      run: cargo check

    - name: Build
      run: |
        set -ex
        cargo build --release
